# Makefile for CS 2150 Pre-Lab 10

a.out: HeapItem.h HeapItem.cpp Heap.h Heap.cpp HeapTest.cpp
	clang++ -o a.out HeapTest.cpp


clean:
	/bin/rm -f *.o *~

# We don't have any dependencies for this small program
